### ISSUE TITLE
Razrada " 3 element battle" sistema

### ISSUE THREAD

**Issue by teoVerbanac** [mhajnic1/PI_Projekt#15]
Potrebno je dogovoriti različite elemnte koji će biti prisutni u igrici sa njihovim korelacijama. Elementi moraju odgovarati navedenom storylineu.

**Potrebno je priložiti txt dokument.**

**Comment by mhajnic1** [comment]
Opis u linku na file:
[elementi.txt](https://github.com/user-attachments/files/15541137/elementi.txt)
